/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppViolationsRouteImport } from './routes/_app/violations'
import { Route as AppStudentsRouteImport } from './routes/_app/students'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClassesRouteImport } from './routes/_app/classes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppViolationsRoute = AppViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/students': typeof AppStudentsRoute
  '/violations': typeof AppViolationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/students': typeof AppStudentsRoute
  '/violations': typeof AppViolationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/violations': typeof AppViolationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/classes'
    | '/dashboard'
    | '/students'
    | '/violations'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/classes' | '/dashboard' | '/students' | '/violations'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/classes'
    | '/_app/dashboard'
    | '/_app/students'
    | '/_app/violations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/violations': {
      id: '/_app/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof AppViolationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClassesRoute: typeof AppClassesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppViolationsRoute: typeof AppViolationsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClassesRoute: AppClassesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppViolationsRoute: AppViolationsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
