/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppViolationsRouteImport } from './routes/_app/violations'
import { Route as AppTeachersRouteImport } from './routes/_app/teachers'
import { Route as AppStudentsRouteImport } from './routes/_app/students'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRewardsRouteImport } from './routes/_app/rewards'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPositiveRouteImport } from './routes/_app/positive'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClassesRouteImport } from './routes/_app/classes'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppActionsRouteImport } from './routes/_app/actions'
import { Route as AppStudentsIdRouteImport } from './routes/_app/students.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppViolationsRoute = AppViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPositiveRoute = AppPositiveRouteImport.update({
  id: '/positive',
  path: '/positive',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppActionsRoute = AppActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIdRoute = AppStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/actions': typeof AppActionsRoute
  '/audit': typeof AppAuditRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/positive': typeof AppPositiveRoute
  '/reports': typeof AppReportsRoute
  '/rewards': typeof AppRewardsRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/teachers': typeof AppTeachersRoute
  '/violations': typeof AppViolationsRoute
  '/students/$id': typeof AppStudentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/actions': typeof AppActionsRoute
  '/audit': typeof AppAuditRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/positive': typeof AppPositiveRoute
  '/reports': typeof AppReportsRoute
  '/rewards': typeof AppRewardsRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/teachers': typeof AppTeachersRoute
  '/violations': typeof AppViolationsRoute
  '/students/$id': typeof AppStudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/actions': typeof AppActionsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/positive': typeof AppPositiveRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/rewards': typeof AppRewardsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/students': typeof AppStudentsRouteWithChildren
  '/_app/teachers': typeof AppTeachersRoute
  '/_app/violations': typeof AppViolationsRoute
  '/_app/students/$id': typeof AppStudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/actions'
    | '/audit'
    | '/classes'
    | '/dashboard'
    | '/positive'
    | '/reports'
    | '/rewards'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/violations'
    | '/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/actions'
    | '/audit'
    | '/classes'
    | '/dashboard'
    | '/positive'
    | '/reports'
    | '/rewards'
    | '/settings'
    | '/students'
    | '/teachers'
    | '/violations'
    | '/students/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/actions'
    | '/_app/audit'
    | '/_app/classes'
    | '/_app/dashboard'
    | '/_app/positive'
    | '/_app/reports'
    | '/_app/rewards'
    | '/_app/settings'
    | '/_app/students'
    | '/_app/teachers'
    | '/_app/violations'
    | '/_app/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/violations': {
      id: '/_app/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof AppViolationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teachers': {
      id: '/_app/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rewards': {
      id: '/_app/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/positive': {
      id: '/_app/positive'
      path: '/positive'
      fullPath: '/positive'
      preLoaderRoute: typeof AppPositiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/actions': {
      id: '/_app/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof AppActionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students/$id': {
      id: '/_app/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AppStudentsIdRouteImport
      parentRoute: typeof AppStudentsRoute
    }
  }
}

interface AppStudentsRouteChildren {
  AppStudentsIdRoute: typeof AppStudentsIdRoute
}

const AppStudentsRouteChildren: AppStudentsRouteChildren = {
  AppStudentsIdRoute: AppStudentsIdRoute,
}

const AppStudentsRouteWithChildren = AppStudentsRoute._addFileChildren(
  AppStudentsRouteChildren,
)

interface AppRouteChildren {
  AppActionsRoute: typeof AppActionsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppClassesRoute: typeof AppClassesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPositiveRoute: typeof AppPositiveRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRewardsRoute: typeof AppRewardsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRouteWithChildren
  AppTeachersRoute: typeof AppTeachersRoute
  AppViolationsRoute: typeof AppViolationsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActionsRoute: AppActionsRoute,
  AppAuditRoute: AppAuditRoute,
  AppClassesRoute: AppClassesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPositiveRoute: AppPositiveRoute,
  AppReportsRoute: AppReportsRoute,
  AppRewardsRoute: AppRewardsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRouteWithChildren,
  AppTeachersRoute: AppTeachersRoute,
  AppViolationsRoute: AppViolationsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
